---
title: "random-cv2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{random-cv2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(sagemaker)
```

```{r}
estimator <- sagemaker_estimator(sagemaker_xgb_container())
```

```{r}
estimator$hyperparam_dict$eval_metric
```


```{r}
split <- list(
  train = s3_path(default_bucket(), "abalone-train.csv"),
  validation = s3_path(default_bucket(), "abalone-test.csv")
)

grid <- list(
  max_depth = sagemaker$tuner$IntegerParameter(3L, 20L),
  colsample_bytree = sagemaker$tuner$ContinuousParameter(0, 1),
  subsample = sagemaker$tuner$ContinuousParameter(0, 1)
)

tune <- sagemaker_hyperparameter_tuner(estimator, split, grid, max_jobs = 1)
```

```{r}
model <- sagemaker_attach_tuner("xgboost-191114-2052")
model
```

```{r}
model
```

```{r}
attached_model_test <- sagemaker_attach_tuner("xgboost-191114-2052")
```

```{r}
attached_model_test
```



```{r}
sagemaker_tuning_job_logs(attached_model_test) %>%
  dplyr::glimpse()
```

```{r}
sagemaker_tuning_job_logs("xgboost-191114-2052") %>% 
  dplyr::glimpse()
```

```{r}
training_logs <- sagemaker_training_job_logs(model$model_name)
```
```{r}
training_logs
```


```{r}
batch_predict(
  model, 
  s3_path(default_bucket(), "abalone-inference.csv"),
  s3_path(default_bucket(), "abalone-transform")
)
```

```{r}
sagemaker_has_endpoint(model)
```

```{r}
sagemaker::abalone %>%
  dplyr::select(-1) %>%
  predict(model, .) %>%
  dplyr::glimpse()
```

```{r}
sagemaker_delete_endpoint(model)
```

```{r}
sagemaker::abalone %>%
  dplyr::select(-1) %>%
  predict(model, .) %>%
  dplyr::glimpse()
```

```{r}
sagemaker_has_endpoint(model)
```

```{r}
tuner <- sagemaker$tuner$HyperparameterTuner$attach("xgboost-191114-2052")
```

```{r}
tuner$latest_tuning_job$job_name
```

```{r}
tuner$estimator$hyperparam_dict$eval_metric
```



